const mediaData = [
  { type: "image", src: "https://files.catbox.moe/g0eps5.jpeg" },
  { type: "image", src: "https://files.catbox.moe/42er2x.jpeg" },
  { type: "image", src: "https://files.catbox.moe/qu8rzl.jpeg" },
  { type: "image", src: "https://files.catbox.moe/wywkdu.jpeg" },
  { type: "image", src: "https://files.catbox.moe/c75cf9.webp" },
  { type: "image", src: "https://files.catbox.moe/pvl5js.jpeg" },
  { type: "image", src: "https://files.catbox.moe/dqbuy7.jpeg" },
  { type: "image", src: "https://files.catbox.moe/0df9c9.jpeg" },
  { type: "image", src: "https://files.catbox.moe/7ac2pq.jpeg" },
  { type: "image", src: "https://files.catbox.moe/34ccz9.jpeg" },
  { type: "image", src: "https://files.catbox.moe/9jq7r2.jpeg" },
  { type: "image", src: "https://files.catbox.moe/y2odyx.jpeg" },
  { type: "image", src: "https://files.catbox.moe/2vc407.jpeg" },
  { type: "image", src: "https://files.catbox.moe/qrq01z.jpeg" },
  { type: "image", src: "https://files.catbox.moe/pdwb8t.jpeg" },
  { type: "image", src: "https://files.catbox.moe/y5jcie.jpeg" },
  { type: "image", src: "https://files.catbox.moe/h9ow8i.jpeg" },
  { type: "image", src: "https://files.catbox.moe/unitmu.jpeg" },
  { type: "image", src: "https://files.catbox.moe/s4z666.jpeg" },
  { type: "image", src: "https://files.catbox.moe/ra7ns3.jpeg" },
  { type: "image", src: "https://files.catbox.moe/5ss93n.jpeg" }
];
