const mediaData = [
  {
    type: 'image',
    url: 'https://files.catbox.moe/g0eps5.jpeg',
    views: 1200,
    likes: 350,
  },
  {
    type: 'image',
    url: 'https://files.catbox.moe/42er2x.jpeg',
    views: 950,
    likes: 210,
  },
  {
    type: 'image',
    url: 'https://files.catbox.moe/qu8rzl.jpeg',
    views: 1100,
    likes: 300,
  },
  {
    type: 'image',
    url: 'https://files.catbox.moe/wywkdu.jpeg',
    views: 800,
    likes: 180,
  },
  {
    type: 'image',
    url: 'https://files.catbox.moe/c75cf9.webp',
    views: 1300,
    likes: 400,
  },
  {
    type: 'image',
    url: 'https://files.catbox.moe/pvl5js.jpeg',
    views: 900,
    likes: 220,
  },
  {
    type: 'image',
    url: 'https://files.catbox.moe/dqbuy7.jpeg',
    views: 950,
    likes: 240,
  },
  {
    type: 'image',
    url: 'https://files.catbox.moe/0df9c9.jpeg',
    views: 1000,
    likes: 270,
  },
  {
    type: 'image',
    url: 'https://files.catbox.moe/7ac2pq.jpeg',
    views: 850,
    likes: 200,
  },
  {
    type: 'image',
    url: 'https://files.catbox.moe/34ccz9.jpeg',
    views: 1100,
    likes: 310,
  },
  {
    type: 'image',
    url: 'https://files.catbox.moe/9jq7r2.jpeg',
    views: 950,
    likes: 230,
  },
  {
    type: 'image',
    url: 'https://files.catbox.moe/y2odyx.jpeg',
    views: 1050,
    likes: 260,
  },
  {
    type: 'image',
    url: 'https://files.catbox.moe/2vc407.jpeg',
    views: 980,
    likes: 210,
  },
  {
    type: 'image',
    url: 'https://files.catbox.moe/qrq01z.jpeg',
    views: 920,
    likes: 180,
  },
  {
    type: 'image',
    url: 'https://files.catbox.moe/pdwb8t.jpeg',
    views: 1100,
    likes: 300,
  },
  {
    type: 'image',
    url: 'https://files.catbox.moe/y5jcie.jpeg',
    views: 1000,
    likes: 250,
  },
  {
    type: 'image',
    url: 'https://files.catbox.moe/h9ow8i.jpeg',
    views: 950,
    likes: 220,
  },
  {
    type: 'image',
    url: 'https://files.catbox.moe/unitmu.jpeg',
    views: 1050,
    likes: 270,
  },
  {
    type: 'image',
    url: 'https://files.catbox.moe/s4z666.jpeg',
    views: 900,
    likes: 210,
  },
  {
    type: 'image',
    url: 'https://files.catbox.moe/ra7ns3.jpeg',
    views: 980,
    likes: 230,
  },
  {
    type: 'image',
    url: 'https://files.catbox.moe/5ss93n.jpeg',
    views: 1100,
    likes: 300,
  },
  {
    type: 'video',
    url: 'https://www.pornhub.com/view_video.php?viewkey=68420206b5aa7#1',
    views: 5000,
    likes: 1500,
  },
];
